# Generated by Django 2.2 on 2020-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20200508_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
