# Generated by Django 2.2 on 2020-05-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_auto_20200508_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='overview',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
